# Generated by Django 4.2.14 on 2024-10-26 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
